Remove unneeded and incorrect ECS service role
Was getting this error when applying:
```
Error: error creating skole-prod-service service: error waiting for ECS
service (skole-prod-service) creation: InvalidParameterException: You
cannot specify an IAM role for services that require a service linked
role.
    on ecs.tf line 9, in resource "aws_ecs_service" "prod":
    9: resource "aws_ecs_service" "prod" {
```